# Generated by Django 3.0 on 2022-03-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
            migrations.SeparateDatabaseAndState(
                database_operations=[
                    # Old table name from checking with sqlmigrate, new table
                    # name from AuthorBook._meta.db_table.
                    migrations.RunSQL(
                        sql='ALTER TABLE oc_lettings_site_profile RENAME TO profiles_profile',
                        reverse_sql='ALTER TABLE profiles_profile RENAME TO oc_lettings_site_profile',
                    ),
                    migrations.RunSQL(
                        sql='ALTER TABLE oc_lettings_site_address RENAME TO lettings_address',
                        reverse_sql='ALTER TABLE lettings_address RENAME TO oc_lettings_site_address',
                    ),
                    migrations.RunSQL(
                        sql='ALTER TABLE oc_lettings_site_letting RENAME TO lettings_letting',
                        reverse_sql='ALTER TABLE lettings_letting RENAME TO oc_lettings_site_letting',
                    ),
                ],
                state_operations=[
                    migrations.RemoveField(
                        model_name='letting',
                        name='address',
                    ),
                    migrations.RemoveField(
                        model_name='profile',
                        name='user',
                    ),
                    migrations.DeleteModel(
                        name='Address',
                    ),
                    migrations.DeleteModel(
                        name='Letting',
                    ),
                    migrations.DeleteModel(
                        name='Profile',
                    ),
                ],
            ),
    ]
